server:
  port: 8091

spring:
  application:
    name: monitoring-service

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/dataforge
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO