version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_DB: dataforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"

  auth-service:
    build:
      context: .
    container_name: auth-service
    depends_on:
      - postgres
    ports:
      - "8088:8088"