version: '3.9'

services:

  postgres:
    image: postgres:16

    container_name: dataforge-postgres

    environment:
      POSTGRES_DB: dataforge_metadata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"